const AVAILABLE_METHODS = [
	// Blockchain
	"getBestBlockHash",
	"getBlock",
	"getBlockchainInfo",
	"getBlockCount",
	"getBlockHash",
	"getBlockHeader",
	"getBlockStats",
	"getChainTips",
	"getChainTxStatus",
	"getDifficulty",
	"getMemPoolAncestors",
	"getMemPoolDescendants",
	"getmemPoolEntry",
	"getMemPoolInfo",
	"getRawMemPool",
	"getTxOut",
	"getTxOutProof",
	"getTxOutSetInfo",
	"preciousBlock",
	"pruneBlockchain",
	"saveMemPool",
	"scanTxOutSet",
	"verifyChain",
	"verifyTxOutProof",

	// control
	"getMemoryInfo",
	"getRpcInfo",
	"help",
	"logging",
	"stop",
	"uptime",

	// generating
	"generate",
	"generateToAddress",

	// mining
	"getBlockTemplate",
	"getMiningInfo",
	"getNetworkHashps",
	"prioritiSetTransaction",
	"submitBlock",
	"submitHeader",

	// network
	"addNode",
	"clearBanned",
	"disconnectNode",
	"getAddedNodeInfo",
	"getConnectionOnCount",
	"getNetTotals",
	"getNetworkInfo",
	"getNodeAddresses",
	"getPeerInfo",
	"listBanned",
	"ping",
	"setBan",
	"setNetworkActive",

	// raw transactions
	"analyzePsbt",
	"combinePsbt",
	"combineRawTransaction",
	"convertToPsbt",
	"createPsbt",
	"createRawTransaction",
	"decodePsbt",
	"decodeRawTransaction",
	"decodeScript",
	"finalizePsbt",
	"fundRawTransaction",
	"getRawTransaction",
	"joinPsbts",
	"sendRawTransaction",
	"signRawTransaction",
	"testMemPoolAccept",
	"utxoUpdatePsbt",
	//util
	"createMultiSig",
	"deriveAddresses",
	"estimateSmartFee",
	"getDescriptorInfo",
	"signMessageWithPrivateKey",
	"validateAddresses",
	"verifyMessage",

	// wallet
	"abandonTransaction",
	"abortRescan",
	"addMultiSigAddress",
	"backupWallet",
	"bumpFee",
	"createWallet",
	"dumpPrivKey",
	"dumpWallet",
	"encryptWallet",
	"getAddressesByLabel",
	"getAddressInfo",
	"getBalance",
	"getNewAddress",
	"getRawChangeAddress",
	"getReceivedByAddress",
	"getReceivedByLabel",
	"getTransaction",
	"getUnconfirmedBalance",
	"getWalletInfo",
	"importAddress",
	"importMulti",
	"importPrivKey",
	"importPrunedFunds",
	"importPubKey",
	"importWallet",
	"keyPoolRefill",
	"listAddressGroupings",
	"listLabels",
	"listLockUnspent",
	"listReceivedByAddress",
	"listReceivedByLabel",
	"listSinceBlock",
	"listTransactions",
	"listUnspent",
	"listWalletDir",
	"listWallets",
	"loadWallet",
	"lockUnspent",
	"removePrunedFunds",
	"rescanBlockchain",
	"sendMany",
	"sendToAddress",
	"setHDSeed",
	"setLabel",
	"setTxFee",
	"signMessage",
	"signRawTransactionWithHDWallet",
	"unloadWallet",
	"walletCreateFundedPsbt",
	"walletLock",
	"walletPassphrase",
	"walletPassphraseChange",
	"walletProcessPsbt",

	//zmq
	"getZmqNotifications"
];

const NETWORKS = {
	mainnet: 9332,
	regtest: 19332,
	testnet: 19332
};

export { AVAILABLE_METHODS, NETWORKS };